version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-app
  mongo:
    image: "mongo:latest"
    restart: always
    volumes:
      - db:/data/db:rw
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "8080:80"

volumes:
  db: